//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPLibClient.LibServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibServiceReference.LibWebServiceSoap")]
    public interface LibWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilterListOfStrings", ReplyAction="*")]
        SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse GetFilterListOfStrings(SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilterListOfStrings", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse> GetFilterListOfStringsAsync(SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilterListOfStringsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterListOfStrings", Namespace="http://tempuri.org/", Order=0)]
        public SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequestBody Body;
        
        public GetFilterListOfStringsRequest() {
        }
        
        public GetFilterListOfStringsRequest(SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilterListOfStringsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public GetFilterListOfStringsRequestBody() {
        }
        
        public GetFilterListOfStringsRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilterListOfStringsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterListOfStringsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponseBody Body;
        
        public GetFilterListOfStringsResponse() {
        }
        
        public GetFilterListOfStringsResponse(SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilterListOfStringsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAPLibClient.LibServiceReference.ArrayOfString GetFilterListOfStringsResult;
        
        public GetFilterListOfStringsResponseBody() {
        }
        
        public GetFilterListOfStringsResponseBody(SOAPLibClient.LibServiceReference.ArrayOfString GetFilterListOfStringsResult) {
            this.GetFilterListOfStringsResult = GetFilterListOfStringsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibWebServiceSoapChannel : SOAPLibClient.LibServiceReference.LibWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibWebServiceSoapClient : System.ServiceModel.ClientBase<SOAPLibClient.LibServiceReference.LibWebServiceSoap>, SOAPLibClient.LibServiceReference.LibWebServiceSoap {
        
        public LibWebServiceSoapClient() {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse SOAPLibClient.LibServiceReference.LibWebServiceSoap.GetFilterListOfStrings(SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest request) {
            return base.Channel.GetFilterListOfStrings(request);
        }
        
        public SOAPLibClient.LibServiceReference.ArrayOfString GetFilterListOfStrings(string keyword) {
            SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest inValue = new SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest();
            inValue.Body = new SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequestBody();
            inValue.Body.keyword = keyword;
            SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse retVal = ((SOAPLibClient.LibServiceReference.LibWebServiceSoap)(this)).GetFilterListOfStrings(inValue);
            return retVal.Body.GetFilterListOfStringsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse> SOAPLibClient.LibServiceReference.LibWebServiceSoap.GetFilterListOfStringsAsync(SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest request) {
            return base.Channel.GetFilterListOfStringsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPLibClient.LibServiceReference.GetFilterListOfStringsResponse> GetFilterListOfStringsAsync(string keyword) {
            SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest inValue = new SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequest();
            inValue.Body = new SOAPLibClient.LibServiceReference.GetFilterListOfStringsRequestBody();
            inValue.Body.keyword = keyword;
            return ((SOAPLibClient.LibServiceReference.LibWebServiceSoap)(this)).GetFilterListOfStringsAsync(inValue);
        }
    }
}
