//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotelibClient.RemoteLibServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteLibServiceReference.RemotelibServiceSoap")]
    public interface RemotelibServiceSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        RemotelibClient.RemoteLibServiceReference.AddBookResponse AddBook(RemotelibClient.RemoteLibServiceReference.AddBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.AddBookResponse> AddBookAsync(RemotelibClient.RemoteLibServiceReference.AddBookRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilteredBooks", ReplyAction="*")]
        RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse GetFilteredBooks(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilteredBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse> GetFilteredBooksAsync(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBook", Namespace="http://tempuri.org/", Order=0)]
        public RemotelibClient.RemoteLibServiceReference.AddBookRequestBody Body;
        
        public AddBookRequest() {
        }
        
        public AddBookRequest(RemotelibClient.RemoteLibServiceReference.AddBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int yop;
        
        public AddBookRequestBody() {
        }
        
        public AddBookRequestBody(string title, string author, int yop) {
            this.title = title;
            this.author = author;
            this.yop = yop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public RemotelibClient.RemoteLibServiceReference.AddBookResponseBody Body;
        
        public AddBookResponse() {
        }
        
        public AddBookResponse(RemotelibClient.RemoteLibServiceReference.AddBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddBookResponseBody {
        
        public AddBookResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilteredBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilteredBooks", Namespace="http://tempuri.org/", Order=0)]
        public RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequestBody Body;
        
        public GetFilteredBooksRequest() {
        }
        
        public GetFilteredBooksRequest(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilteredBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public GetFilteredBooksRequestBody() {
        }
        
        public GetFilteredBooksRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilteredBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilteredBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponseBody Body;
        
        public GetFilteredBooksResponse() {
        }
        
        public GetFilteredBooksResponse(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilteredBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RemotelibClient.RemoteLibServiceReference.ArrayOfString GetFilteredBooksResult;
        
        public GetFilteredBooksResponseBody() {
        }
        
        public GetFilteredBooksResponseBody(RemotelibClient.RemoteLibServiceReference.ArrayOfString GetFilteredBooksResult) {
            this.GetFilteredBooksResult = GetFilteredBooksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RemotelibServiceSoapChannel : RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemotelibServiceSoapClient : System.ServiceModel.ClientBase<RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap>, RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap {
        
        public RemotelibServiceSoapClient() {
        }
        
        public RemotelibServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemotelibServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemotelibServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemotelibServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemotelibClient.RemoteLibServiceReference.AddBookResponse RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap.AddBook(RemotelibClient.RemoteLibServiceReference.AddBookRequest request) {
            return base.Channel.AddBook(request);
        }
        
        public void AddBook(string title, string author, int yop) {
            RemotelibClient.RemoteLibServiceReference.AddBookRequest inValue = new RemotelibClient.RemoteLibServiceReference.AddBookRequest();
            inValue.Body = new RemotelibClient.RemoteLibServiceReference.AddBookRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.yop = yop;
            RemotelibClient.RemoteLibServiceReference.AddBookResponse retVal = ((RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap)(this)).AddBook(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.AddBookResponse> RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap.AddBookAsync(RemotelibClient.RemoteLibServiceReference.AddBookRequest request) {
            return base.Channel.AddBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.AddBookResponse> AddBookAsync(string title, string author, int yop) {
            RemotelibClient.RemoteLibServiceReference.AddBookRequest inValue = new RemotelibClient.RemoteLibServiceReference.AddBookRequest();
            inValue.Body = new RemotelibClient.RemoteLibServiceReference.AddBookRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.yop = yop;
            return ((RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap)(this)).AddBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap.GetFilteredBooks(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest request) {
            return base.Channel.GetFilteredBooks(request);
        }
        
        public RemotelibClient.RemoteLibServiceReference.ArrayOfString GetFilteredBooks(string keyword) {
            RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest inValue = new RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest();
            inValue.Body = new RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequestBody();
            inValue.Body.keyword = keyword;
            RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse retVal = ((RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap)(this)).GetFilteredBooks(inValue);
            return retVal.Body.GetFilteredBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse> RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap.GetFilteredBooksAsync(RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest request) {
            return base.Channel.GetFilteredBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemotelibClient.RemoteLibServiceReference.GetFilteredBooksResponse> GetFilteredBooksAsync(string keyword) {
            RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest inValue = new RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequest();
            inValue.Body = new RemotelibClient.RemoteLibServiceReference.GetFilteredBooksRequestBody();
            inValue.Body.keyword = keyword;
            return ((RemotelibClient.RemoteLibServiceReference.RemotelibServiceSoap)(this)).GetFilteredBooksAsync(inValue);
        }
    }
}
