//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Quiz2ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Quiz2ServiceReference.Quiz2WebServiceSoap")]
    public interface Quiz2WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPerson", ReplyAction="*")]
        WpfApplication1.Quiz2ServiceReference.addPersonResponse addPerson(WpfApplication1.Quiz2ServiceReference.addPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.addPersonResponse> addPersonAsync(WpfApplication1.Quiz2ServiceReference.addPersonRequest request);
        
        // CODEGEN: Generating message contract since element name nameSearch from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersons", ReplyAction="*")]
        WpfApplication1.Quiz2ServiceReference.getPersonsResponse getPersons(WpfApplication1.Quiz2ServiceReference.getPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.getPersonsResponse> getPersonsAsync(WpfApplication1.Quiz2ServiceReference.getPersonsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPerson", Namespace="http://tempuri.org/", Order=0)]
        public WpfApplication1.Quiz2ServiceReference.addPersonRequestBody Body;
        
        public addPersonRequest() {
        }
        
        public addPersonRequest(WpfApplication1.Quiz2ServiceReference.addPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int height;
        
        public addPersonRequestBody() {
        }
        
        public addPersonRequestBody(string name, int age, int height) {
            this.name = name;
            this.age = age;
            this.height = height;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApplication1.Quiz2ServiceReference.addPersonResponseBody Body;
        
        public addPersonResponse() {
        }
        
        public addPersonResponse(WpfApplication1.Quiz2ServiceReference.addPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addPersonResponseBody {
        
        public addPersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersons", Namespace="http://tempuri.org/", Order=0)]
        public WpfApplication1.Quiz2ServiceReference.getPersonsRequestBody Body;
        
        public getPersonsRequest() {
        }
        
        public getPersonsRequest(WpfApplication1.Quiz2ServiceReference.getPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameSearch;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int minAge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int maxAge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int minHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int maxHeight;
        
        public getPersonsRequestBody() {
        }
        
        public getPersonsRequestBody(string nameSearch, int minAge, int maxAge, int minHeight, int maxHeight) {
            this.nameSearch = nameSearch;
            this.minAge = minAge;
            this.maxAge = maxAge;
            this.minHeight = minHeight;
            this.maxHeight = maxHeight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApplication1.Quiz2ServiceReference.getPersonsResponseBody Body;
        
        public getPersonsResponse() {
        }
        
        public getPersonsResponse(WpfApplication1.Quiz2ServiceReference.getPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApplication1.Quiz2ServiceReference.ArrayOfString getPersonsResult;
        
        public getPersonsResponseBody() {
        }
        
        public getPersonsResponseBody(WpfApplication1.Quiz2ServiceReference.ArrayOfString getPersonsResult) {
            this.getPersonsResult = getPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Quiz2WebServiceSoapChannel : WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Quiz2WebServiceSoapClient : System.ServiceModel.ClientBase<WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap>, WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap {
        
        public Quiz2WebServiceSoapClient() {
        }
        
        public Quiz2WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Quiz2WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Quiz2WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Quiz2WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.Quiz2ServiceReference.addPersonResponse WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap.addPerson(WpfApplication1.Quiz2ServiceReference.addPersonRequest request) {
            return base.Channel.addPerson(request);
        }
        
        public void addPerson(string name, int age, int height) {
            WpfApplication1.Quiz2ServiceReference.addPersonRequest inValue = new WpfApplication1.Quiz2ServiceReference.addPersonRequest();
            inValue.Body = new WpfApplication1.Quiz2ServiceReference.addPersonRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.height = height;
            WpfApplication1.Quiz2ServiceReference.addPersonResponse retVal = ((WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap)(this)).addPerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.addPersonResponse> WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap.addPersonAsync(WpfApplication1.Quiz2ServiceReference.addPersonRequest request) {
            return base.Channel.addPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.addPersonResponse> addPersonAsync(string name, int age, int height) {
            WpfApplication1.Quiz2ServiceReference.addPersonRequest inValue = new WpfApplication1.Quiz2ServiceReference.addPersonRequest();
            inValue.Body = new WpfApplication1.Quiz2ServiceReference.addPersonRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.height = height;
            return ((WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap)(this)).addPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.Quiz2ServiceReference.getPersonsResponse WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap.getPersons(WpfApplication1.Quiz2ServiceReference.getPersonsRequest request) {
            return base.Channel.getPersons(request);
        }
        
        public WpfApplication1.Quiz2ServiceReference.ArrayOfString getPersons(string nameSearch, int minAge, int maxAge, int minHeight, int maxHeight) {
            WpfApplication1.Quiz2ServiceReference.getPersonsRequest inValue = new WpfApplication1.Quiz2ServiceReference.getPersonsRequest();
            inValue.Body = new WpfApplication1.Quiz2ServiceReference.getPersonsRequestBody();
            inValue.Body.nameSearch = nameSearch;
            inValue.Body.minAge = minAge;
            inValue.Body.maxAge = maxAge;
            inValue.Body.minHeight = minHeight;
            inValue.Body.maxHeight = maxHeight;
            WpfApplication1.Quiz2ServiceReference.getPersonsResponse retVal = ((WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap)(this)).getPersons(inValue);
            return retVal.Body.getPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.getPersonsResponse> WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap.getPersonsAsync(WpfApplication1.Quiz2ServiceReference.getPersonsRequest request) {
            return base.Channel.getPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.Quiz2ServiceReference.getPersonsResponse> getPersonsAsync(string nameSearch, int minAge, int maxAge, int minHeight, int maxHeight) {
            WpfApplication1.Quiz2ServiceReference.getPersonsRequest inValue = new WpfApplication1.Quiz2ServiceReference.getPersonsRequest();
            inValue.Body = new WpfApplication1.Quiz2ServiceReference.getPersonsRequestBody();
            inValue.Body.nameSearch = nameSearch;
            inValue.Body.minAge = minAge;
            inValue.Body.maxAge = maxAge;
            inValue.Body.minHeight = minHeight;
            inValue.Body.maxHeight = maxHeight;
            return ((WpfApplication1.Quiz2ServiceReference.Quiz2WebServiceSoap)(this)).getPersonsAsync(inValue);
        }
    }
}
