//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLib_csharp_client.LibraryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryServiceReference.LibWebServiceSoap")]
    public interface LibWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse AddBook(RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse> AddBookAsync(RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilterListOfStrings", ReplyAction="*")]
        RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse GetFilterListOfStrings(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilterListOfStrings", ReplyAction="*")]
        System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse> GetFilterListOfStringsAsync(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBook", Namespace="http://tempuri.org/", Order=0)]
        public RemoteLib_csharp_client.LibraryServiceReference.AddBookRequestBody Body;
        
        public AddBookRequest() {
        }
        
        public AddBookRequest(RemoteLib_csharp_client.LibraryServiceReference.AddBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int yop;
        
        public AddBookRequestBody() {
        }
        
        public AddBookRequestBody(string title, string author, int yop) {
            this.title = title;
            this.author = author;
            this.yop = yop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public RemoteLib_csharp_client.LibraryServiceReference.AddBookResponseBody Body;
        
        public AddBookResponse() {
        }
        
        public AddBookResponse(RemoteLib_csharp_client.LibraryServiceReference.AddBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddBookResult;
        
        public AddBookResponseBody() {
        }
        
        public AddBookResponseBody(int AddBookResult) {
            this.AddBookResult = AddBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilterListOfStringsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterListOfStrings", Namespace="http://tempuri.org/", Order=0)]
        public RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequestBody Body;
        
        public GetFilterListOfStringsRequest() {
        }
        
        public GetFilterListOfStringsRequest(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilterListOfStringsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public GetFilterListOfStringsRequestBody() {
        }
        
        public GetFilterListOfStringsRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilterListOfStringsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterListOfStringsResponse", Namespace="http://tempuri.org/", Order=0)]
        public RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponseBody Body;
        
        public GetFilterListOfStringsResponse() {
        }
        
        public GetFilterListOfStringsResponse(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFilterListOfStringsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RemoteLib_csharp_client.LibraryServiceReference.ArrayOfString GetFilterListOfStringsResult;
        
        public GetFilterListOfStringsResponseBody() {
        }
        
        public GetFilterListOfStringsResponseBody(RemoteLib_csharp_client.LibraryServiceReference.ArrayOfString GetFilterListOfStringsResult) {
            this.GetFilterListOfStringsResult = GetFilterListOfStringsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibWebServiceSoapChannel : RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibWebServiceSoapClient : System.ServiceModel.ClientBase<RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap>, RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap {
        
        public LibWebServiceSoapClient() {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap.AddBook(RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest request) {
            return base.Channel.AddBook(request);
        }
        
        public int AddBook(string title, string author, int yop) {
            RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest inValue = new RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest();
            inValue.Body = new RemoteLib_csharp_client.LibraryServiceReference.AddBookRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.yop = yop;
            RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse retVal = ((RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap)(this)).AddBook(inValue);
            return retVal.Body.AddBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse> RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap.AddBookAsync(RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest request) {
            return base.Channel.AddBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.AddBookResponse> AddBookAsync(string title, string author, int yop) {
            RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest inValue = new RemoteLib_csharp_client.LibraryServiceReference.AddBookRequest();
            inValue.Body = new RemoteLib_csharp_client.LibraryServiceReference.AddBookRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.yop = yop;
            return ((RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap)(this)).AddBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap.GetFilterListOfStrings(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest request) {
            return base.Channel.GetFilterListOfStrings(request);
        }
        
        public RemoteLib_csharp_client.LibraryServiceReference.ArrayOfString GetFilterListOfStrings(string keyword) {
            RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest inValue = new RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest();
            inValue.Body = new RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequestBody();
            inValue.Body.keyword = keyword;
            RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse retVal = ((RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap)(this)).GetFilterListOfStrings(inValue);
            return retVal.Body.GetFilterListOfStringsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse> RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap.GetFilterListOfStringsAsync(RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest request) {
            return base.Channel.GetFilterListOfStringsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsResponse> GetFilterListOfStringsAsync(string keyword) {
            RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest inValue = new RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequest();
            inValue.Body = new RemoteLib_csharp_client.LibraryServiceReference.GetFilterListOfStringsRequestBody();
            inValue.Body.keyword = keyword;
            return ((RemoteLib_csharp_client.LibraryServiceReference.LibWebServiceSoap)(this)).GetFilterListOfStringsAsync(inValue);
        }
    }
}
